/**招标合同 */
export const TENDER_CONTRACT = [
  'TENDER_PURCHASE_CONTRACT',
  'TENDER_FRAMEWORK_PACT',
];

/**框架协议合同 */
export const EXECUTION_CONTRACT = [
  'EXECUTION_CONTRACT',
  'NO_TENDER_EXECUTION_CONTRACT',
];
